name: Build mipsel static

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake git wget

    - name: Download musl toolchain
      run: |
        wget  -4 https://musl.cc/mipsel-linux-muslsf-cross.tgz
        tar -xzf mipsel-linux-muslsf-cross.tgz

    - name: Build
      run: |
        export PATH=$PWD/mipsel-linux-muslsf-cross/bin:$PATH
        mkdir build && cd build
        cmake .. \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_C_COMPILER=mipsel-linux-muslsf-gcc \
          -DCMAKE_EXE_LINKER_FLAGS="-static" \
          -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hev-socks5-tunnel-mipsel
        path: build/hev-socks5-tunnel
